In [1]:
print("Smart shopping cart project started!")

Smart shopping cart project started!

In [2]:
import os
print(os.getcwd())

c:\Users\Nilabha\OneDrive\Desktop\SmartShoppingCart\notebooks

In [3]:
import pandas as pd

In [4]:
products = pd.read_csv("../data/phase1/products.csv")
products.head()

,product_id,product_name,category,subcategory,brand,price,market_price,product_type,rating,description
0,P000001,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,P000002,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,P000003,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,P000004,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,P000005,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [6]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    27555 non-null  object
 1   product_name  27554 non-null  object
 2   category      27555 non-null  object
 3   subcategory   27555 non-null  object
 4   brand         27554 non-null  object
 5   price         27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   product_type  27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), object(7)
memory usage: 2.1+ MB

In [7]:
products.isnull().sum()

product_id         0
product_name       1
category           0
subcategory        0
brand              1
price              0
market_price       0
product_type       0
rating          8626
description      115
dtype: int64

In [8]:
products["category"].value_counts()

category
Beauty & Hygiene            7867
Gourmet & World Food        4690
Kitchen, Garden & Pets      3580
Snacks & Branded Foods      2814
Foodgrains, Oil & Masala    2676
Cleaning & Household        2675
Beverages                    885
Bakery, Cakes & Dairy        851
Baby Care                    610
Fruits & Vegetables          557
Eggs, Meat & Fish            350
Name: count, dtype: int64

In [10]:
products["product_id"].nunique()

27555

In [11]:
len(products)

27555

In [12]:
products[["product_id", "product_name", "category", "subcategory", "brand", "price", "rating"]].head(10)

,product_id,product_name,category,subcategory,brand,price,rating
0,P000001,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,4.1
1,P000002,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,2.3
2,P000003,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,3.4
3,P000004,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,3.7
4,P000005,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,4.4
5,P000006,Germ - Removal Multipurpose Wipes,Cleaning & Household,All Purpose Cleaners,Nature Protect,169.0,3.3
6,P000007,Multani Mati,Beauty & Hygiene,Skin Care,Satinance,58.0,3.6
7,P000008,Hand Sanitizer - 70% Alcohol Base,Beauty & Hygiene,Bath & Hand Wash,Bionova,250.0,4.0
8,P000009,Biotin & Collagen Volumizing Hair Shampoo + Bi...,Beauty & Hygiene,Hair Care,StBotanica,1098.0,3.5
9,P000010,"Scrub Pad - Anti- Bacterial, Regular",Cleaning & Household,"Mops, Brushes & Scrubs",Scotch brite,20.0,4.3

In [13]:
products["description"].head(10)

0    This Product contains Garlic Oil that is known...
1    Each product is microwave safe (without lid), ...
2    A perfect gift for all occasions, be it your m...
3    Multipurpose container with an attractive desi...
4    Nivea Creme Soft Soap gives your skin the best...
5    Stay protected from contamination with Multipu...
6    Satinance multani matti is an excellent skin t...
7    70%Alcohol based is gentle of hand leaves skin...
8    An exclusive blend with Vitamin B7 Biotin, Hyd...
9    Scotch Brite Anti- Bacterial Scrub Pad thoroug...
Name: description, dtype: object

In [14]:
products[products["product_name"].isna()]

,product_id,product_name,category,subcategory,brand,price,market_price,product_type,rating,description
14363,P014364,NaN,Beverages,Coffee,Cothas Coffee,200.0,240.0,Ground Coffee,4.2,Cothas Specialty Blend Coffee and Chicory incl...

In [15]:
products[products["brand"].isna()]

,product_id,product_name,category,subcategory,brand,price,market_price,product_type,rating,description
9765,P009766,Food Package - Medium,Cleaning & Household,"Disposables, Garbage Bag",NaN,50.0,50.0,"Aluminium Foil, Clingwrap",NaN,NaN

In [16]:
products["rating"].describe()

count    18929.000000
mean         3.943410
std          0.739063
min          1.000000
25%          3.700000
50%          4.100000
75%          4.300000
max          5.000000
Name: rating, dtype: float64

In [17]:
products[products["description"].isna()][["product_id", "product_name", "category", "subcategory", "brand"]]

,product_id,product_name,category,subcategory,brand
288,P000289,Arrabbiata Tomato Pasta Sauce With Chilli,Gourmet & World Food,"Sauces, Spreads & Dips",Montanini
480,P000481,"Pumice Stone & Emery Foot Filer - FFL3407, Col...",Beauty & Hygiene,Bath & Hand Wash,Kaiv
780,P000781,Peanut Butter - Chunky,Gourmet & World Food,"Sauces, Spreads & Dips",American Garden
845,P000846,Squash - Sarasaparilla/Nannari/Sugandhi Root,Beverages,Fruit Juices & Drinks,NaturoBell
1047,P001048,"Natura Rice & Walnut Drink, Vegan",Gourmet & World Food,Drinks & Beverages,BORGES
...,...,...,...,...,...
25510,P025511,BBPopular Almond/Badam Californian 500gm + BBR...,"Foodgrains, Oil & Masala",Dry Fruits,bb Combo
25583,P025584,Chai/Chai/Tea/ Coffee Bone China Microwave Ser...,"Kitchen, Garden & Pets",Crockery & Cutlery,BP Bharat
26116,P026117,"Tea Strainer - Stainless Steel, Medium","Kitchen, Garden & Pets",Kitchen Accessories,Ritu
26835,P026836,Cold Pressed Virgin Groundnut Oil,"Foodgrains, Oil & Masala",Edible Oils & Ghee,Chekko
27303,P027304,Zipper Storage - Gallon,Cleaning & Household,"Disposables, Garbage Bag",Glad

In [19]:
products.duplicated(subset=["product_name", "brand"], keep=False).sum()

5441

In [21]:
nutrition = pd.read_csv("../data/phase1/product_nutrition.csv")
nutrition.head()

,product_id,serving_basis_g,calories_kcal,protein_g,carbohydrates_g,sugar_g,fat_g,saturated_fat_g,fiber_g,sodium_mg
0,P000001,100,731.3,2.1,0.0,0.0,99.0,18.6,0.0,0.0
1,P000002,100,64.6,1.9,15.7,9.1,1.2,0.0,3.7,9.1
2,P000003,100,713.3,1.9,0.0,0.0,109.9,17.7,0.0,0.0
3,P000004,100,324.7,23.7,48.4,3.1,3.0,0.8,9.1,53.2
4,P000005,100,232.0,7.8,26.9,7.9,8.7,3.5,3.3,166.1

In [22]:
set(nutrition["product_id"])-set(products["product_id"])

set()

In [23]:
attributes = pd.read_csv("../data/phase1/product_attributes.csv")
attributes.head()

,product_id,vegetarian,vegan,gluten_free,contains_milk,contains_nuts,contains_soy,health_tags
0,P000001,True,True,True,False,False,False,low_sugar
1,P000002,True,True,True,False,False,False,low_calorie
2,P000003,True,True,True,False,False,False,low_sugar
3,P000004,True,True,True,False,False,False,"high_protein,low_sugar,high_fiber"
4,P000005,True,True,True,False,False,False,standard

In [24]:
set(attributes["product_id"]) - set(products["product_id"])

set()

In [25]:
transactions = pd.read_csv("../data/phase1/transactions.csv")
transactions.head()

,transaction_id,customer_id,product_id,purchase_date,quantity,unit_price,total_price
0,T0000001,C02389,P023096,24-06-2026,1,349.0,349.0
1,T0000002,C00130,P012708,27-05-2025,1,62.5,62.5
2,T0000003,C00639,P013070,27-08-2025,1,342.0,342.0
3,T0000004,C02976,P024212,23-05-2025,1,30.0,30.0
4,T0000005,C01630,P024501,23-01-2026,2,162.0,324.0

In [26]:
set(transactions["product_id"]) - set(products["product_id"])

set()

In [28]:
transactions["customer_id"].nunique()

3000

In [29]:
transactions["customer_id"].value_counts().describe()

count    3000.000000
mean       40.000000
std         6.366436
min        19.000000
25%        36.000000
50%        40.000000
75%        44.000000
max        63.000000
Name: count, dtype: float64

In [30]:
transactions.columns.tolist()

['transaction_id',
 'customer_id',
 'product_id',
 'purchase_date',
 'quantity',
 'unit_price',
 'total_price']

In [31]:
master_products = products.merge(nutrition, on="product_id", how="left").merge(attributes, on="product_id", how="left")
master_products.head()

,product_id,product_name,category,subcategory,brand,price,market_price,product_type,rating,description,...,saturated_fat_g,fiber_g,sodium_mg,vegetarian,vegan,gluten_free,contains_milk,contains_nuts,contains_soy,health_tags
0,P000001,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...,...,18.6,0.0,0.0,True,True,True,False,False,False,low_sugar
1,P000002,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ...",...,0.0,3.7,9.1,True,True,True,False,False,False,low_calorie
2,P000003,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m...",...,17.7,0.0,0.0,True,True,True,False,False,False,low_sugar
3,P000004,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...,...,0.8,9.1,53.2,True,True,True,False,False,False,"high_protein,low_sugar,high_fiber"
4,P000005,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...,...,3.5,3.3,166.1,True,True,True,False,False,False,standard

In [32]:
master_products.shape

(27555, 26)

In [33]:
master_products.to_csv("../data/phase1/master_products.csv", index = False)

In [34]:
user_items = transactions[["customer_id", "product_id", "quantity", "purchase_date"]].copy()
user_items.head()

  customer_id product_id  quantity purchase_date
0      C02389    P023096         1    24-06-2026
1      C00130    P012708         1    27-05-2025
2      C00639    P013070         1    27-08-2025
3      C02976    P024212         1    23-05-2025
4      C01630    P024501         2    23-01-2026

In [35]:
user_items[["customer_id", "product_id"]].drop_duplicates().shape

(119925, 2)

In [37]:
popular_products = (transactions.groupby("product_id")["quantity"].sum().sort_values(ascending = False))
popular_products.head(10)

product_id
P014780    27
P017469    26
P018480    26
P015094    24
P002722    24
P022320    24
P015814    23
P009886    22
P013595    22
P009840    22
Name: quantity, dtype: int64

In [38]:
popular_recommendations = (popular_products.head(10).reset_index().merge(master_products, on="product_id", how="left"))
popular_recommendations[["product_id", "product_name", "category", "brand", "price", "rating", "quantity"]]

,product_id,product_name,category,brand,price,rating,quantity
0,P014780,"Rusk - Suji & Elaichi, 200 g + TGL Co.Kadak Ma...","Bakery, Cakes & Dairy",Tasties,209.3,NaN,27
1,P017469,Fruit Power Juice - Mango,Beverages,Real,20.0,NaN,26
2,P018480,Skinguard Manual Shaving Razor Blades,Beauty & Hygiene,Gillette,472.5,4.3,26
3,P015094,Perfume Body Spray - Enchanted Antense For Women,Beauty & Hygiene,Armaf,475.0,NaN,24
4,P002722,Rice Water Brightening Scrub,Beauty & Hygiene,Glamveda,208.0,4.2,24
5,P022320,Freshness Gel Natural Ayurvedic Cardamom Tooth...,Beauty & Hygiene,Lever Ayush,40.0,4.3,24
6,P015814,Bib - Ice Cream Printed,Baby Care,Morison Baby Dreams,125.0,NaN,23
7,P009886,Steel Cut Oats - Gluten Free,Gourmet & World Food,True Elements,292.0,NaN,22
8,P013595,Potato Chips - Rock Sea Salt & English Vinegar,Gourmet & World Food,Kettle Studio,40.0,3.5,22
9,P009840,Grapeseed Oil Smoothing Hair Serum - Leave-On,Beauty & Hygiene,Aloe Veda,351.0,4.7,22

In [40]:
def recommend_popular(n=5):
    return popular_recommendations[["product_id", "product_name", "category", "brand", "price", "rating", "quantity"]].head(n)

In [41]:
recommend_popular(5)

,product_id,product_name,category,brand,price,rating,quantity
0,P014780,"Rusk - Suji & Elaichi, 200 g + TGL Co.Kadak Ma...","Bakery, Cakes & Dairy",Tasties,209.3,NaN,27
1,P017469,Fruit Power Juice - Mango,Beverages,Real,20.0,NaN,26
2,P018480,Skinguard Manual Shaving Razor Blades,Beauty & Hygiene,Gillette,472.5,4.3,26
3,P015094,Perfume Body Spray - Enchanted Antense For Women,Beauty & Hygiene,Armaf,475.0,NaN,24
4,P002722,Rice Water Brightening Scrub,Beauty & Hygiene,Glamveda,208.0,4.2,24

In [42]:
popular_recommendations.to_csv("../models/popular_baseline.csv", index=False)