In [2]:
import pandas as pd

master_products = pd.read_csv("../data/phase1/master_products.csv")

interactions = pd.read_csv("../data/phase2/customer_product_interactions.csv")

content_products = pd.read_csv(
    "../models/content_based/content_products.csv"
)
collab_recommendations = pd.read_csv(
    "../models/collaborative_candidates_C00001.csv"
)

In [3]:
content_products.columns.tolist()

['product_id',
 'product_name',
 'category',
 'subcategory',
 'brand',
 'product_type',
 'description',
 'combined_features']

In [4]:
import os
os.listdir("../models/content_based")

['content_products.csv', 'tfidf_matrix.npz', 'tfidf_vectorizer.pkl']

In [5]:
import joblib
from scipy.sparse import load_npz

tfidf_matrix = load_npz(
    "../models/content_based/tfidf_matrix.npz"
)

tfidf = joblib.load(
    "../models/content_based/tfidf_vectorizer.pkl"
)

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
customer_id = "C00001"

purchased_products = interactions[
    interactions["customer_id"] == customer_id
]["product_id"].unique()
purchased_indices = content_products[
    content_products["product_id"].isin(purchased_products)
].index
candidate_indices = content_products[
    content_products["product_id"].isin(collab_recommendations["product_id"])
].index

content_scores = cosine_similarity(
    tfidf_matrix[candidate_indices],
    tfidf_matrix[purchased_indices]
).max(axis=1)

collab_recommendations["content_score"] = content_scores
collab_recommendations.head(10)

,product_id,collaborative_score,product_name,category,brand,price,rating,content_score
0,P026388,0.155126,"Shower Sponge - Lemon & White, Colour May Vary",Beauty & Hygiene,Panache,159.2,4.0,0.118010
1,P010637,0.103418,Water Juice Glass Set - Salsa Hi Ball,"Kitchen, Garden & Pets",Ocean,679.0,3.0,0.143938
2,P014337,0.103418,Bio Aloevera Lotion - 30 Spf Sunscreen For Nor...,Beauty & Hygiene,BIOTIQUE,188.0,4.0,0.061709
3,P026457,0.103418,Pickle - Garlic,Snacks & Branded Foods,Nirapara,135.0,3.7,0.124596
4,P017394,0.103418,So Soft 3 Ply - Toilet Tissue Rolls,Cleaning & Household,Origami,310.0,4.2,0.138429
5,P011377,0.103418,"Dry Dog Food - PRO, Expert Nutrition for Activ...","Kitchen, Garden & Pets",Pedigree,2700.0,4.8,0.203335
6,P022821,0.103418,Large Period Cup For Medium Or Heavy Flow - Po...,Beauty & Hygiene,ezy,439.2,3.7,0.078531
7,P000801,0.051709,Premium - 3 Follow-Up Formula,Baby Care,Dexolac,595.0,4.5,0.417582
8,P019543,0.051709,D-Tan Scrub For Men,Beauty & Hygiene,QRAA,263.0,4.2,0.064228
9,P022417,0.051709,Chalk Gold - For Cockroaches,Cleaning & Household,Krazy Lines,25.0,3.6,0.031126

In [7]:
collab_recommendations["hybrid_score"] = (
    0.6 * collab_recommendations["collaborative_score"] + 0.4 * collab_recommendations["content_score"]
)
collab_recommendations = collab_recommendations.sort_values(
    "hybrid_score", ascending=False
)
collab_recommendations.head(10)

,product_id,collaborative_score,product_name,category,brand,price,rating,content_score,hybrid_score
7,P000801,0.051709,Premium - 3 Follow-Up Formula,Baby Care,Dexolac,595.0,4.5,0.417582,0.198058
15,P026869,0.051709,Anti-Ageing Night Cream,Beauty & Hygiene,INATUR,337.5,1.0,0.321588,0.159661
31,P026894,0.051709,Vitamin C Foaming Brightening Face Wash - With...,Beauty & Hygiene,StBotanica,445.0,4.7,0.292085,0.147859
5,P011377,0.103418,"Dry Dog Food - PRO, Expert Nutrition for Activ...","Kitchen, Garden & Pets",Pedigree,2700.0,4.8,0.203335,0.143385
0,P026388,0.155126,"Shower Sponge - Lemon & White, Colour May Vary",Beauty & Hygiene,Panache,159.2,4.0,0.118010,0.140280
29,P003744,0.051709,Pizza Cutter - Royal,"Kitchen, Garden & Pets",Anjali,50.0,3.9,0.271730,0.139717
12,P023445,0.051709,FIAMA Shower Gel Lemongrass Jojoba 100ml + FIA...,Beauty & Hygiene,Fiama,108.9,NaN,0.258456,0.134408
1,P010637,0.103418,Water Juice Glass Set - Salsa Hi Ball,"Kitchen, Garden & Pets",Ocean,679.0,3.0,0.143938,0.119626
4,P017394,0.103418,So Soft 3 Ply - Toilet Tissue Rolls,Cleaning & Household,Origami,310.0,4.2,0.138429,0.117422
11,P016052,0.051709,Frankincense Essential Oil,Beauty & Hygiene,Nectar Valley,465.0,3.0,0.212628,0.116076

In [8]:
interaction_matrix = interactions.pivot_table(
    index = "customer_id",
    columns = "product_id", 
    values = "total_quantity",
    aggfunc = "sum",
    fill_value=0
)
print(interaction_matrix.shape)

(3000, 27145)

In [9]:
binary_interaction = (interaction_matrix>0).astype(int)
print("Binary interaction matrix shape:", binary_interaction.shape)

Binary interaction matrix shape: (3000, 27145)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
customer_similarity = cosine_similarity(binary_interaction)
print("Customer similarity matrix shape:", customer_similarity.shape)

Customer similarity matrix shape: (3000, 3000)

In [11]:
import numpy as np
def collaborative_candidates(customer_id, n_similar=20, n_candidates=50):
    customer_index=interaction_matrix.index.get_loc(customer_id)
    similarity_scores = customer_similarity[customer_index]
    similar_indices = np.argsort(similarity_scores)[::-1]
    candidates={}
    processed_similar = 0
    for i in similar_indices:
        similar_customers = interaction_matrix.index[i]
        if similar_customers == customer_id:
            continue
        similarity = similarity_scores[i]
        customer_products = interaction_matrix.loc[similar_customers]
        purchased_products = customer_products[customer_products>0]
        for product_id, quantity in purchased_products.items():
            if interaction_matrix.loc[customer_id, product_id]>0:
                continue
            score = similarity*quantity
            candidates[product_id] = (candidates.get(product_id, 0) + score)
        processed_similar+=1
        if processed_similar >= n_similar:
            break    
        
    recommendations = (
        pd.DataFrame(
            list(candidates.items()),
            columns=["product_id", "collaborative_score"]
        )
        .sort_values(
            "collaborative_score",
            ascending=False
        )
        .head(n_candidates)
    )
    return recommendations

In [12]:
collab_test = collaborative_candidates(
    "C00001", n_similar=20, n_candidates=50
) 
collab_test.head(10)

    product_id  collaborative_score
91     P015536             0.190693
26     P026388             0.155126
10     P010637             0.151091
33     P004097             0.148704
54     P016702             0.148704
67     P000237             0.143019
70     P002553             0.143019
102    P026493             0.143019
97     P021849             0.143019
88     P012599             0.143019

In [13]:
def hybrid_recommend(customer_id, n=10):
    purchased_products = interactions[
        interactions["customer_id"] == customer_id
    ]["product_id"].unique()

    collab_candidates = collaborative_candidates(
        customer_id, n_similar=20, n_candidates=50
    )

    collab_candidates = collab_candidates.merge(
        master_products[
            [
                "product_id",
                "product_name",
                "category",
                "brand",
                "price",
                "rating"
            ]
        ],
        on="product_id",
        how="left"
    )

    product_to_index = pd.Series(
        content_products.index,
        index=content_products["product_id"]
    )

    purchased_indices = [
        product_to_index[p]
        for p in purchased_products
        if p in product_to_index.index
    ]

    candidate_indices = [
        product_to_index[p]
        for p in collab_candidates["product_id"]
        if p in product_to_index.index
    ]

    if purchased_indices and candidate_indices:
        content_scores = cosine_similarity(
            tfidf_matrix[candidate_indices],
            tfidf_matrix[purchased_indices]
        ).max(axis=1)
    else:
        content_scores = np.zeros(len(collab_candidates))

    collab_candidates["content_scores"] = content_scores

    from sklearn.preprocessing import MinMaxScaler

    scaler = MinMaxScaler()

    collab_candidates[
        ["collaborative_score", "content_scores"]
    ] = scaler.fit_transform(
        collab_candidates[
            ["collaborative_score", "content_scores"]
        ]
    )

    collab_candidates["hybrid_score"] = (
        0.6 * collab_candidates["collaborative_score"]
        + 0.4 * collab_candidates["content_scores"]
    )

    recommendations = collab_candidates.sort_values(
        "hybrid_score",
        ascending=False
    ).head(n)

    return recommendations[
        [
            "product_id",
            "product_name",
            "category",
            "brand",
            "price",
            "rating",
            "collaborative_score",
            "content_scores",
            "hybrid_score"
        ]
    ]

In [19]:
all_recommendations = []

for customer_id in interactions["customer_id"].unique():
    customer_recommendations = hybrid_recommend(customer_id, n=10)

    customer_recommendations["customer_id"] = customer_id
    all_recommendations.append(customer_recommendations)
    print("Processed:", customer_id)
print("customers processed:", len(all_recommendations))

Processed: C00001
Processed: C00002
Processed: C00003
Processed: C00004
Processed: C00005
Processed: C00006
Processed: C00007
Processed: C00008
Processed: C00009
Processed: C00010
Processed: C00011
Processed: C00012
Processed: C00013
Processed: C00014
Processed: C00015
Processed: C00016
Processed: C00017
Processed: C00018
Processed: C00019
Processed: C00020
Processed: C00021
Processed: C00022
Processed: C00023
Processed: C00024
Processed: C00025
Processed: C00026
Processed: C00027
Processed: C00028
Processed: C00029
Processed: C00030
Processed: C00031
Processed: C00032
Processed: C00033
Processed: C00034
Processed: C00035
Processed: C00036
Processed: C00037
Processed: C00038
Processed: C00039
Processed: C00040
Processed: C00041
Processed: C00042
Processed: C00043
Processed: C00044
Processed: C00045
Processed: C00046
Processed: C00047
Processed: C00048
Processed: C00049
Processed: C00050
Processed: C00051
Processed: C00052
Processed: C00053
Processed: C00054
Processed: C00055
Processed: C00056
Processed: C00057
Processed: C00058
Processed: C00059
Processed: C00060
Processed: C00061
Processed: C00062
Processed: C00063
Processed: C00064
Processed: C00065
Processed: C00066
Processed: C00067
Processed: C00068
Processed: C00069
Processed: C00070
Processed: C00071
Processed: C00072
Processed: C00073
Processed: C00074
Processed: C00075
Processed: C00076
Processed: C00077
Processed: C00078
Processed: C00079
Processed: C00080
Processed: C00081
Processed: C00082
Processed: C00083
Processed: C00084
Processed: C00085
Processed: C00086
Processed: C00087
Processed: C00088
Processed: C00089
Processed: C00090
Processed: C00091
Processed: C00092
Processed: C00093
Processed: C00094
Processed: C00095
Processed: C00096
Processed: C00097
Processed: C00098
Processed: C00099
Processed: C00100
Processed: C00101
Processed: C00102
Processed: C00103
Processed: C00104
Processed: C00105
Processed: C00106
Processed: C00107
Processed: C00108
Processed: C00109
Processed: C00110
Processed: C00111
Processed: C00112
Processed: C00113
Processed: C00114
Processed: C00115
Processed: C00116
Processed: C00117
Processed: C00118
Processed: C00119
Processed: C00120
Processed: C00121
Processed: C00122
Processed: C00123
Processed: C00124
Processed: C00125
Processed: C00126
Processed: C00127
Processed: C00128
Processed: C00129
Processed: C00130
Processed: C00131
Processed: C00132
Processed: C00133
Processed: C00134
Processed: C00135
Processed: C00136
Processed: C00137
Processed: C00138
Processed: C00139
Processed: C00140
Processed: C00141
Processed: C00142
Processed: C00143
Processed: C00144
Processed: C00145
Processed: C00146
Processed: C00147
Processed: C00148
Processed: C00149
Processed: C00150
Processed: C00151
Processed: C00152
Processed: C00153
Processed: C00154
Processed: C00155
Processed: C00156
Processed: C00157
Processed: C00158
Processed: C00159
Processed: C00160
Processed: C00161
Processed: C00162
Processed: C00163
Processed: C00164
Processed: C00165
Processed: C00166
Processed: C00167
Processed: C00168
Processed: C00169
Processed: C00170
Processed: C00171
Processed: C00172
Processed: C00173
Processed: C00174
Processed: C00175
Processed: C00176
Processed: C00177
Processed: C00178
Processed: C00179
Processed: C00180
Processed: C00181
Processed: C00182
Processed: C00183
Processed: C00184
Processed: C00185
Processed: C00186
Processed: C00187
Processed: C00188
Processed: C00189
Processed: C00190
Processed: C00191
Processed: C00192
Processed: C00193
Processed: C00194
Processed: C00195
Processed: C00196
Processed: C00197
Processed: C00198
Processed: C00199
Processed: C00200
Processed: C00201
Processed: C00202
Processed: C00203
Processed: C00204
Processed: C00205
Processed: C00206
Processed: C00207
Processed: C00208
Processed: C00209
Processed: C00210
Processed: C00211
Processed: C00212
Processed: C00213
Processed: C00214
Processed: C00215
Processed: C00216
Processed: C00217
Processed: C00218
Processed: C00219
Processed: C00220
Processed: C00221
Processed: C00222
Processed: C00223
Processed: C00224
Processed: C00225
Processed: C00226
Processed: C00227
Processed: C00228
Processed: C00229
Processed: C00230
Processed: C00231
Processed: C00232
Processed: C00233
Processed: C00234
Processed: C00235
Processed: C00236
Processed: C00237
Processed: C00238
Processed: C00239
Processed: C00240
Processed: C00241
Processed: C00242
Processed: C00243
Processed: C00244
Processed: C00245
Processed: C00246
Processed: C00247
Processed: C00248
Processed: C00249
Processed: C00250
Processed: C00251
Processed: C00252
Processed: C00253
Processed: C00254
Processed: C00255
Processed: C00256
Processed: C00257
Processed: C00258
Processed: C00259
Processed: C00260
Processed: C00261
Processed: C00262
Processed: C00263
Processed: C00264
Processed: C00265
Processed: C00266
Processed: C00267
Processed: C00268
Processed: C00269
Processed: C00270
Processed: C00271
Processed: C00272
Processed: C00273
Processed: C00274
Processed: C00275
Processed: C00276
Processed: C00277
Processed: C00278
Processed: C00279
Processed: C00280
Processed: C00281
Processed: C00282
Processed: C00283
Processed: C00284
Processed: C00285
Processed: C00286
Processed: C00287
Processed: C00288
Processed: C00289
Processed: C00290
Processed: C00291
Processed: C00292
Processed: C00293
Processed: C00294
Processed: C00295
Processed: C00296
Processed: C00297
Processed: C00298
Processed: C00299
Processed: C00300
Processed: C00301
Processed: C00302
Processed: C00303
Processed: C00304
Processed: C00305
Processed: C00306
Processed: C00307
Processed: C00308
Processed: C00309
Processed: C00310
Processed: C00311
Processed: C00312
Processed: C00313
Processed: C00314
Processed: C00315
Processed: C00316
Processed: C00317
Processed: C00318
Processed: C00319
Processed: C00320
Processed: C00321
Processed: C00322
Processed: C00323
Processed: C00324
Processed: C00325
Processed: C00326
Processed: C00327
Processed: C00328
Processed: C00329
Processed: C00330
Processed: C00331
Processed: C00332
Processed: C00333
Processed: C00334
Processed: C00335
Processed: C00336
Processed: C00337
Processed: C00338
Processed: C00339
Processed: C00340
Processed: C00341
Processed: C00342
Processed: C00343
Processed: C00344
Processed: C00345
Processed: C00346
Processed: C00347
Processed: C00348
Processed: C00349
Processed: C00350
Processed: C00351
Processed: C00352
Processed: C00353
Processed: C00354
Processed: C00355
Processed: C00356
Processed: C00357
Processed: C00358
Processed: C00359
Processed: C00360
Processed: C00361
Processed: C00362
Processed: C00363
Processed: C00364
Processed: C00365
Processed: C00366
Processed: C00367
Processed: C00368
Processed: C00369
Processed: C00370
Processed: C00371
Processed: C00372
Processed: C00373
Processed: C00374
Processed: C00375
Processed: C00376
Processed: C00377
Processed: C00378
Processed: C00379
Processed: C00380
Processed: C00381
Processed: C00382
Processed: C00383
Processed: C00384
Processed: C00385
Processed: C00386
Processed: C00387
Processed: C00388
Processed: C00389
Processed: C00390
Processed: C00391
Processed: C00392
Processed: C00393
Processed: C00394
Processed: C00395
Processed: C00396
Processed: C00397
Processed: C00398
Processed: C00399
Processed: C00400
Processed: C00401
Processed: C00402
Processed: C00403
Processed: C00404
Processed: C00405
Processed: C00406
Processed: C00407
Processed: C00408
Processed: C00409
Processed: C00410
Processed: C00411
Processed: C00412
Processed: C00413
Processed: C00414
Processed: C00415
Processed: C00416
Processed: C00417
Processed: C00418
Processed: C00419
Processed: C00420
Processed: C00421
Processed: C00422
Processed: C00423
Processed: C00424
Processed: C00425
Processed: C00426
Processed: C00427
Processed: C00428
Processed: C00429
Processed: C00430
Processed: C00431
Processed: C00432
Processed: C00433
Processed: C00434
Processed: C00435
Processed: C00436
Processed: C00437
Processed: C00438
Processed: C00439
Processed: C00440
Processed: C00441
Processed: C00442
Processed: C00443
Processed: C00444
Processed: C00445
Processed: C00446
Processed: C00447
Processed: C00448
Processed: C00449
Processed: C00450
Processed: C00451
Processed: C00452
Processed: C00453
Processed: C00454
Processed: C00455
Processed: C00456
Processed: C00457
Processed: C00458
Processed: C00459
Processed: C00460
Processed: C00461
Processed: C00462
Processed: C00463
Processed: C00464
Processed: C00465
Processed: C00466
Processed: C00467
Processed: C00468
Processed: C00469
Processed: C00470
Processed: C00471
Processed: C00472
Processed: C00473
Processed: C00474
Processed: C00475
Processed: C00476
Processed: C00477
Processed: C00478
Processed: C00479
Processed: C00480
Processed: C00481
Processed: C00482
Processed: C00483
Processed: C00484
Processed: C00485
Processed: C00486
Processed: C00487
Processed: C00488
Processed: C00489
Processed: C00490
Processed: C00491
Processed: C00492
Processed: C00493
Processed: C00494
Processed: C00495
Processed: C00496
Processed: C00497
Processed: C00498
Processed: C00499
Processed: C00500
Processed: C00501
Processed: C00502
Processed: C00503
Processed: C00504
Processed: C00505
Processed: C00506
Processed: C00507
Processed: C00508
Processed: C00509
Processed: C00510
Processed: C00511
Processed: C00512
Processed: C00513
Processed: C00514
Processed: C00515
Processed: C00516
Processed: C00517
Processed: C00518
Processed: C00519
Processed: C00520
Processed: C00521
Processed: C00522
Processed: C00523
Processed: C00524
Processed: C00525
Processed: C00526
Processed: C00527
Processed: C00528
Processed: C00529
Processed: C00530
Processed: C00531
Processed: C00532
Processed: C00533
Processed: C00534
Processed: C00535
Processed: C00536
Processed: C00537
Processed: C00538
Processed: C00539
Processed: C00540
Processed: C00541
Processed: C00542
Processed: C00543
Processed: C00544
Processed: C00545
Processed: C00546
Processed: C00547
Processed: C00548
Processed: C00549
Processed: C00550
Processed: C00551
Processed: C00552
Processed: C00553
Processed: C00554
Processed: C00555
Processed: C00556
Processed: C00557
Processed: C00558
Processed: C00559
Processed: C00560
Processed: C00561
Processed: C00562
Processed: C00563
Processed: C00564
Processed: C00565
Processed: C00566
Processed: C00567
Processed: C00568
Processed: C00569
Processed: C00570
Processed: C00571
Processed: C00572
Processed: C00573
Processed: C00574
Processed: C00575
Processed: C00576
Processed: C00577
Processed: C00578
Processed: C00579
Processed: C00580
Processed: C00581
Processed: C00582
Processed: C00583
Processed: C00584
Processed: C00585
Processed: C00586
Processed: C00587
Processed: C00588
Processed: C00589
Processed: C00590
Processed: C00591
Processed: C00592
Processed: C00593
Processed: C00594
Processed: C00595
Processed: C00596
Processed: C00597
Processed: C00598
Processed: C00599
Processed: C00600
Processed: C00601
Processed: C00602
Processed: C00603
Processed: C00604
Processed: C00605
Processed: C00606
Processed: C00607
Processed: C00608
Processed: C00609
Processed: C00610
Processed: C00611
Processed: C00612
Processed: C00613
Processed: C00614
Processed: C00615
Processed: C00616
Processed: C00617
Processed: C00618
Processed: C00619
Processed: C00620
Processed: C00621
Processed: C00622
Processed: C00623
Processed: C00624
Processed: C00625
Processed: C00626
Processed: C00627
Processed: C00628
Processed: C00629
Processed: C00630
Processed: C00631
Processed: C00632
Processed: C00633
Processed: C00634
Processed: C00635
Processed: C00636
Processed: C00637
Processed: C00638
Processed: C00639
Processed: C00640
Processed: C00641
Processed: C00642
Processed: C00643
Processed: C00644
Processed: C00645
Processed: C00646
Processed: C00647
Processed: C00648
Processed: C00649
Processed: C00650
Processed: C00651
Processed: C00652
Processed: C00653
Processed: C00654
Processed: C00655
Processed: C00656
Processed: C00657
Processed: C00658
Processed: C00659
Processed: C00660
Processed: C00661
Processed: C00662
Processed: C00663
Processed: C00664
Processed: C00665
Processed: C00666
Processed: C00667
Processed: C00668
Processed: C00669
Processed: C00670
Processed: C00671
Processed: C00672
Processed: C00673
Processed: C00674
Processed: C00675
Processed: C00676
Processed: C00677
Processed: C00678
Processed: C00679
Processed: C00680
Processed: C00681
Processed: C00682
Processed: C00683
Processed: C00684
Processed: C00685
Processed: C00686
Processed: C00687
Processed: C00688
Processed: C00689
Processed: C00690
Processed: C00691
Processed: C00692
Processed: C00693
Processed: C00694
Processed: C00695
Processed: C00696
Processed: C00697
Processed: C00698
Processed: C00699
Processed: C00700
Processed: C00701
Processed: C00702
Processed: C00703
Processed: C00704
Processed: C00705
Processed: C00706
Processed: C00707
Processed: C00708
Processed: C00709
Processed: C00710
Processed: C00711
Processed: C00712
Processed: C00713
Processed: C00714
Processed: C00715
Processed: C00716
Processed: C00717
Processed: C00718
Processed: C00719
Processed: C00720
Processed: C00721
Processed: C00722
Processed: C00723
Processed: C00724
Processed: C00725
Processed: C00726
Processed: C00727
Processed: C00728
Processed: C00729
Processed: C00730
Processed: C00731
Processed: C00732
Processed: C00733
Processed: C00734
Processed: C00735
Processed: C00736
Processed: C00737
Processed: C00738
Processed: C00739
Processed: C00740
Processed: C00741
Processed: C00742
Processed: C00743
Processed: C00744
Processed: C00745
Processed: C00746
Processed: C00747
Processed: C00748
Processed: C00749
Processed: C00750
Processed: C00751
Processed: C00752
Processed: C00753
Processed: C00754
Processed: C00755
Processed: C00756
Processed: C00757
Processed: C00758
Processed: C00759
Processed: C00760
Processed: C00761
Processed: C00762
Processed: C00763
Processed: C00764
Processed: C00765
Processed: C00766
Processed: C00767
Processed: C00768
Processed: C00769
Processed: C00770
Processed: C00771
Processed: C00772
Processed: C00773
Processed: C00774
Processed: C00775
Processed: C00776
Processed: C00777
Processed: C00778
Processed: C00779
Processed: C00780
Processed: C00781
Processed: C00782
Processed: C00783
Processed: C00784
Processed: C00785
Processed: C00786
Processed: C00787
Processed: C00788
Processed: C00789
Processed: C00790
Processed: C00791
Processed: C00792
Processed: C00793
Processed: C00794
Processed: C00795
Processed: C00796
Processed: C00797
Processed: C00798
Processed: C00799
Processed: C00800
Processed: C00801
Processed: C00802
Processed: C00803
Processed: C00804
Processed: C00805
Processed: C00806
Processed: C00807
Processed: C00808
Processed: C00809
Processed: C00810
Processed: C00811
Processed: C00812
Processed: C00813
Processed: C00814
Processed: C00815
Processed: C00816
Processed: C00817
Processed: C00818
Processed: C00819
Processed: C00820
Processed: C00821
Processed: C00822
Processed: C00823
Processed: C00824
Processed: C00825
Processed: C00826
Processed: C00827
Processed: C00828
Processed: C00829
Processed: C00830
Processed: C00831
Processed: C00832
Processed: C00833
Processed: C00834
Processed: C00835
Processed: C00836
Processed: C00837
Processed: C00838
Processed: C00839
Processed: C00840
Processed: C00841
Processed: C00842
Processed: C00843
Processed: C00844
Processed: C00845
Processed: C00846
Processed: C00847
Processed: C00848
Processed: C00849
Processed: C00850
Processed: C00851
Processed: C00852
Processed: C00853
Processed: C00854
Processed: C00855
Processed: C00856
Processed: C00857
Processed: C00858
Processed: C00859
Processed: C00860
Processed: C00861
Processed: C00862
Processed: C00863
Processed: C00864
Processed: C00865
Processed: C00866
Processed: C00867
Processed: C00868
Processed: C00869
Processed: C00870
Processed: C00871
Processed: C00872
Processed: C00873
Processed: C00874
Processed: C00875
Processed: C00876
Processed: C00877
Processed: C00878
Processed: C00879
Processed: C00880
Processed: C00881
Processed: C00882
Processed: C00883
Processed: C00884
Processed: C00885
Processed: C00886
Processed: C00887
Processed: C00888
Processed: C00889
Processed: C00890
Processed: C00891
Processed: C00892
Processed: C00893
Processed: C00894
Processed: C00895
Processed: C00896
Processed: C00897
Processed: C00898
Processed: C00899
Processed: C00900
Processed: C00901
Processed: C00902
Processed: C00903
Processed: C00904
Processed: C00905
Processed: C00906
Processed: C00907
Processed: C00908
Processed: C00909
Processed: C00910
Processed: C00911
Processed: C00912
Processed: C00913
Processed: C00914
Processed: C00915
Processed: C00916
Processed: C00917
Processed: C00918
Processed: C00919
Processed: C00920
Processed: C00921
Processed: C00922
Processed: C00923
Processed: C00924
Processed: C00925
Processed: C00926
Processed: C00927
Processed: C00928
Processed: C00929
Processed: C00930
Processed: C00931
Processed: C00932
Processed: C00933
Processed: C00934
Processed: C00935
Processed: C00936
Processed: C00937
Processed: C00938
Processed: C00939
Processed: C00940
Processed: C00941
Processed: C00942
Processed: C00943
Processed: C00944
Processed: C00945
Processed: C00946
Processed: C00947
Processed: C00948
Processed: C00949
Processed: C00950
Processed: C00951
Processed: C00952
Processed: C00953
Processed: C00954
Processed: C00955
Processed: C00956
Processed: C00957
Processed: C00958
Processed: C00959
Processed: C00960
Processed: C00961
Processed: C00962
Processed: C00963
Processed: C00964
Processed: C00965
Processed: C00966
Processed: C00967
Processed: C00968
Processed: C00969
Processed: C00970
Processed: C00971
Processed: C00972
Processed: C00973
Processed: C00974
Processed: C00975
Processed: C00976
Processed: C00977
Processed: C00978
Processed: C00979
Processed: C00980
Processed: C00981
Processed: C00982
Processed: C00983
Processed: C00984
Processed: C00985
Processed: C00986
Processed: C00987
Processed: C00988
Processed: C00989
Processed: C00990
Processed: C00991
Processed: C00992
Processed: C00993
Processed: C00994
Processed: C00995
Processed: C00996
Processed: C00997
Processed: C00998
Processed: C00999
Processed: C01000
Processed: C01001
Processed: C01002
Processed: C01003
Processed: C01004
Processed: C01005
Processed: C01006
Processed: C01007
Processed: C01008
Processed: C01009
Processed: C01010
Processed: C01011
Processed: C01012
Processed: C01013
Processed: C01014
Processed: C01015
Processed: C01016
Processed: C01017
Processed: C01018
Processed: C01019
Processed: C01020
Processed: C01021
Processed: C01022
Processed: C01023
Processed: C01024
Processed: C01025
Processed: C01026
Processed: C01027
Processed: C01028
Processed: C01029
Processed: C01030
Processed: C01031
Processed: C01032
Processed: C01033
Processed: C01034
Processed: C01035
Processed: C01036
Processed: C01037
Processed: C01038
Processed: C01039
Processed: C01040
Processed: C01041
Processed: C01042
Processed: C01043
Processed: C01044
Processed: C01045
Processed: C01046
Processed: C01047
Processed: C01048
Processed: C01049
Processed: C01050
Processed: C01051
Processed: C01052
Processed: C01053
Processed: C01054
Processed: C01055
Processed: C01056
Processed: C01057
Processed: C01058
Processed: C01059
Processed: C01060
Processed: C01061
Processed: C01062
Processed: C01063
Processed: C01064
Processed: C01065
Processed: C01066
Processed: C01067
Processed: C01068
Processed: C01069
Processed: C01070
Processed: C01071
Processed: C01072
Processed: C01073
Processed: C01074
Processed: C01075
Processed: C01076
Processed: C01077
Processed: C01078
Processed: C01079
Processed: C01080
Processed: C01081
Processed: C01082
Processed: C01083
Processed: C01084
Processed: C01085
Processed: C01086
Processed: C01087
Processed: C01088
Processed: C01089
Processed: C01090
Processed: C01091
Processed: C01092
Processed: C01093
Processed: C01094
Processed: C01095
Processed: C01096
Processed: C01097
Processed: C01098
Processed: C01099
Processed: C01100
Processed: C01101
Processed: C01102
Processed: C01103
Processed: C01104
Processed: C01105
Processed: C01106
Processed: C01107
Processed: C01108
Processed: C01109
Processed: C01110
Processed: C01111

In [15]:
recommendations = hybrid_recommend("C00001", n=10)
recommendations

,product_id,product_name,category,brand,price,rating,collaborative_score,content_scores,hybrid_score
5,P000237,Raw Seeds - Sunflower Pumpkin Flax Seeds,Gourmet & World Food,True Elements,166.00,4.4,0.522234,1.000000,0.713340
0,P015536,Belgian Chocolate Cookies,"Bakery, Cakes & Dairy",FabBox,250.00,3.2,1.000000,0.142944,0.657178
12,P009846,Regrowth Hair Oil,Beauty & Hygiene,INATUR,296.00,NaN,0.455532,0.819045,0.600937
9,P012599,Jamnagar Chunda Achar,Snacks & Branded Foods,Graminway,159.00,2.6,0.522234,0.305170,0.435409
3,P004097,Special K,Snacks & Branded Foods,Kelloggs,210.00,4.2,0.579208,0.213032,0.432738
2,P010637,Water Juice Glass Set - Salsa Hi Ball,"Kitchen, Garden & Pets",Ocean,679.00,3.0,0.603122,0.136934,0.416647
1,P026388,"Shower Sponge - Lemon & White, Colour May Vary",Beauty & Hygiene,Panache,159.20,4.0,0.643566,0.040658,0.402403
6,P002553,Celeste Coffret For Women,Beauty & Hygiene,Skinn by Titan,1610.25,4.7,0.522234,0.161743,0.378038
7,P026493,Mealmaker Masala Soya Mini Chunks,"Foodgrains, Oil & Masala",Saffola,45.00,4.5,0.522234,0.128154,0.364602
8,P021849,Noodles - Vegetable,Gourmet & World Food,Koka,94.50,4.3,0.522234,0.088479,0.348732

In [20]:
all_recommendations_df = pd.concat(
    all_recommendations,
    ignore_index=True
)
print("Total recommendation rows:", len(all_recommendations_df))
print("Unique customers:", all_recommendations_df["customer_id"].nunique())
all_recommendations_df.head()

Total recommendation rows: 30000
Unique customers: 3000

,product_id,product_name,category,brand,price,rating,collaborative_score,content_scores,hybrid_score,customer_id
0,P000237,Raw Seeds - Sunflower Pumpkin Flax Seeds,Gourmet & World Food,True Elements,166.0,4.4,0.522234,1.000000,0.713340,C00001
1,P015536,Belgian Chocolate Cookies,"Bakery, Cakes & Dairy",FabBox,250.0,3.2,1.000000,0.142944,0.657178,C00001
2,P009846,Regrowth Hair Oil,Beauty & Hygiene,INATUR,296.0,NaN,0.455532,0.819045,0.600937,C00001
3,P012599,Jamnagar Chunda Achar,Snacks & Branded Foods,Graminway,159.0,2.6,0.522234,0.305170,0.435409,C00001
4,P004097,Special K,Snacks & Branded Foods,Kelloggs,210.0,4.2,0.579208,0.213032,0.432738,C00001

In [16]:
recommendations.to_csv("../models/hybid_recommendations_C00001.csv", index=False)

In [21]:
all_recommendations_df.to_csv(
    "../models/hybrid_recommendations_all_customers.csv",
    index=False
)
print("All-customer hybrid recommendations saved successfully.")

All-customer hybrid recommendations saved successfully.